#' @export
GenerateConditions <- function(n){
  sample(
    list(
      Gene(c("attack-soldier-count", "condition"), c(relop(), Pick1(0:100))),
      Gene(c("attack-warboat-count", "condition"), c(relop(), Pick1(0:50))),
      Gene(c("building-available", "condition"), building()),
      Gene(c("true", "condition")),
      Gene(c("building-type-count", "condition"), c(building(), relop(), Pick1(0:5))), # building-count crashes?
      Gene(c("building-type-count-total", "condition"), c(building(), relop(), Pick1(0:5))),
      Gene(c("building-type-count-total", "condition"), c(building(), relop(), Pick1(0:5))),
      Gene(c("can-afford-building", "condition"), building()),
      Gene(c("can-afford-complete-wall", "condition"), c(perimeter(), wallType())),
      Gene(c("can-afford-research", "condition"), researchItem()),
      Gene(c("can-afford-unit", "condition"), unit()),
      Gene(c("can-build", "condition"), building()),
      Gene(c("can-build-gate", "condition"), perimeter()),
      Gene(c("can-build-gate-with-escrow", "condition"), perimeter()),
      Gene(c("can-build-wall", "condition"), c(perimeter(), wallType())),
      Gene(c("can-build-wall-with-escrow", "condition"), c(perimeter(), wallType())),
      Gene(c("can-build-with-escrow", "condition"), building()),
      Gene(c("can-buy-commodity", "condition"), commodity()),
      Gene(c("can-research", "condition"), researchItem()),
      Gene(c("can-research-with-escrow", "condition"), researchItem()),
      Gene(c("can-sell-commodity", "condition"), commodity()),
      Gene(c("can-spy", "condition")),
      Gene(c("can-spy-with-escrow", "condition")),
      Gene(c("can-train", "condition"), unit()),
      Gene(c("can-train-with-escrow", "condition"), unit()),
      Gene(c("civilian-population", "condition"), c(relop(), Pick1(0:100))),
      Gene(c("civ-selected", "condition"), civ()),
      Gene(c("commodity-buying-price", "condition"), c(commodity(), relop(), Pick1(0:200))),
      Gene(c("commodity-selling-price", "condition"), c(commodity(), relop(), Pick1(0:200))),
      Gene(c("current-age", "condition"), c(relop(), age())),
      Gene(c("current-age-time", "condition"), c(relop(), Pick1(0:1000))),
      Gene(c("current-score", "condition"), c(relop(), Pick1(0:100000))),
      Gene(c("death-match-game", "condition")),
      Gene(c("defend-soldier-count", "condition"), c(relop(), Pick1(0:100))),
      Gene(c("defend-warboat-count", "condition"), c(relop(), Pick1(0:50))),
      Gene(c("dropsiteMinDistance", "condition"), c(resourceType(), relop(), Pick1(0:50))),
      Gene(c("enemy-buildings-in-town", "condition")),
      Gene(c("enemy-captured-relics", "condition")),
      Gene(c("escrowAmount", "condition"), c(resourceType(), relop(), Pick1(0:1500))),
      Gene(c("food-amount", "condition"), c(relop(), Pick1(0:1000))),
      Gene(c("game-time", "condition"), c(relop(), Pick1(0:10000))),
      Gene(c("game-type", "condition"), c(relop(), gameType())),
      Gene(c("gate-count", "condition"), c(perimeter(), relop(), Pick1(0:10))),
      Gene(c("goal", "condition"), c(goalId(), Pick1(0:10))),
      Gene(c("gold-amount", "condition"), c(relop(), Pick1(0:1500))),
      Gene(c("hold-relics", "condition")),
      Gene(c("hold-koh-ruin", "condition")),
      Gene(c("housing-headroom", "condition"), c(relop(), Pick1(0:30))),
      Gene(c("idle-farm-count", "condition"), c(relop(), Pick1(0:4))),
      Gene(c("map-size", "condition"), mapSize()),
      Gene(c("map-type", "condition"), mapType()),
      Gene(c("military-population", "condition"), c(relop(), Pick1(0:150))),
      Gene(c("players-building-count", "condition"), c(playerNumber(), relop(), Pick1(0:25))),
      Gene(c("players-building-type-count", "condition"), c(playerNumber(), building(), relop(), Pick1(0:5))),
      Gene(c("players-civ", "condition"), c(playerNumber(), civ())),
      Gene(c("players-civilian-population", "condition"), c(playerNumber(), relop(), Pick1(0:100))),
      Gene(c("players-current-age", "condition"), c(playerNumber(), relop(), age())),
      Gene(c("players-current-age-time", "condition"), c(playerNumber(), relop(), Pick1(0:1000))),
      Gene(c("players-military-population", "condition"), c(playerNumber(), relop(), Pick1(0:150))),
      Gene(c("players-population", "condition"), c(playerNumber(), relop(), Pick1(0:250))),
      Gene(c("players-score", "condition"), c(playerNumber(), relop(), Pick1(0:10000))),
      Gene(c("players-stance", "condition"), c(playerNumber(), diplomaticStance())),
      Gene(c("playersTribute", "condition"), c(playerNumber(), resourceType(), relop(), Pick1(0:1000))),
      Gene(c("playersTributeMemory", "condition"), c(playerNumber(), resourceType(), relop(), Pick1(0:1000))),
      Gene(c("players-unit-count", "condition"), c(playerNumber(), relop(), Pick1(0:250))),
      Gene(c("players-unit-type-count", "condition"), c(playerNumber(), unit(), relop(), Pick1(0:25))),
      Gene(c("population", "condition"), c(relop(), Pick1(0:250))),
      Gene(c("population-cap", "condition"), c(relop(), Pick1(0:500))),
      Gene(c("population-headroom", "condition"), c(relop(), Pick1(0:25))),
      Gene(c("random-number", "condition"), c(relop(), Pick1(1:10))),
      # Gene(c("regicide-game", "condition")), Nothing wrong with it but I'm not going to train on regicide games specifically so this will only break genes
      Gene(c("research-available", "condition"), researchItem()),
      Gene(c("research-completed", "condition"), researchItem()),
      Gene(c("resourceFound", "condition"), resourceType()),
      Gene(c("shared-goal", "condition"), c(sharedGoalId(), Pick1(0:10))),
      Gene(c("sheep-and-forage-too-far", "condition")),
      Gene(c("soldier-count", "condition"), c(relop(), Pick1(0:150))),
      Gene(c("stance-toward", "condition"), c(playerNumber(), diplomaticStance())),
      Gene(c("starting-age", "condition"), c(relop(), age())),
      Gene(c("starting-resources", "condition"), c(relop(), startingResources())),
      Gene(c("stone-amount", "condition"), c(relop(), Pick1(0:1500))),
      Gene(c("timer-triggered", "condition"), timerId()),
      Gene(c("town-under-attack", "condition")),
      Gene(c("unit-available", "condition"), unit()),
      Gene(c("unit-count", "condition"), c(relop(), Pick1(0:250))),
      Gene(c("unit-count-total", "condition"), c(relop(), Pick1(0:250))),
      Gene(c("unit-type-count", "condition"), c(unit(), relop(), Pick1(0:25))),
      Gene(c("unit-type-count-total", "condition"), c(unit(), relop(), Pick1(0:25))),
      # Gene(c("victory-condition", "condition"), victoryCondition()),
      Gene(c("wall-completed-percentage", "condition"), c(perimeter(), relop(), Pick1(0:100))),
      Gene(c("wall-invisible-percentage", "condition"), c(perimeter(), relop(), Pick1(0:100))),
      Gene(c("warboat-count", "condition"), c(relop(), Pick1(0:50))),
      Gene(c("wood-amount", "condition"), c(relop(), Pick1(0:1500)))
    ),
    n
  )
}
